var aMD_5545=new Array('www.avantlink','www.jameco','www.rockler');var aMI_5545=new Array('10048','10609','11533');var aNP_5545=new Array('avantlink.com/click.php','avantlink.com/gbi/','avantlink.com/tpv/','avantlink.com/ptc','avantlink.com/syndicate','avantlink.com/coupons','avantlink.com/product_display','avantlink.com/product_showcase','avantlink.ca/click.php','avantlink.ca/gbi/','avantlink.ca/tpv/','avantlink.ca/ptc','avantlink.ca/syndicate','avantlink.ca/coupons','avantlink.ca/product_display','avantlink.ca/product_showcase','avantlink.com.au/click.php','avantlink.com.au/gbi/','avantlink.com.au/tpv/','avantlink.com.au/ptc','avantlink.com.au/syndicate','avantlink.com.au/coupons','avantlink.com.au/product_display','avantlink.com.au/product_showcase');
function avEncodeLinks_5545(){var links=document.getElementsByTagName('a');var anchorHtml='';var bAle=0;for(var i=0; i<links.length; i++){var curLink=links[i];var aParts=curLink.href.split('?');aParts[0]=aParts[0].toLowerCase();bAle=0;if(aParts[0].indexOf('http')==0){var iPos=aParts[0].indexOf('://');if(iPos > 0){var aUrlPieces=aParts[0].substring(iPos+3).split('/');var sUrlTest=aUrlPieces[0];for(var j=0; j<aMD_5545.length; j++){if(sUrlTest.indexOf(aMD_5545[j])==0 || sUrlTest.indexOf('.'+aMD_5545[j])> 0){bAle=1;if(aMI_5545[j]==10048 || aMI_5545[j]==11177){for(var k=0; k<aNP_5545.length; k++){if(aParts[0].indexOf(aNP_5545[k])>= 0){bAle=0; break;}}}if(bAle==1){try{anchorHtml=curLink.innerHTML;curLink.href="http://www.avantlink.com/click.php?tt=ale&ti=5545&pri=0&pw=158237&mi="+aMI_5545[j]+"&url="+encodeURIComponent(curLink.href);curLink.innerHTML=anchorHtml;}catch(e){}}break;}}}}}}
function avInitiateAle_5545(){avEncodeLinks_5545();return;}
function OnDOMLoad_5545(A11,A12) { var A0 = false; var A1 = false; var A2 = false; var A3 = false; var A4 = false; var A5 = null; var A6 = null; if (typeof A11 != "function") { return; } if (typeof A12 == "undefined") { A12 = window; A6 = window.document; } else { A6 = A12.document; } A9(); if (A2) { A6.addEventListener("DOMContentLoaded", A10, null); } else if (A1) { var src = "src='javascript:void(0)'"; if (A6.location.protocol == "https:") { src = "src=//0"; } A6.write("<script id='DOMLoadScript' defer " + src + "><\/script>"); var A7 = A6.getElementById("DOMLoadScript"); var A13 = A7.onreadystatechange; A7.onreadystatechange = function() { if (typeof A13 == "function") { A13(); } if (A7.readyState == "complete") { A7.onreadystatechange = null; A7.removeNode(true); A10(); } }; } else if (A3) { A5 = A12.setInterval(function() { if (/loaded|complete/.test(A6.readyState)) { A10(); } }, 10); return; } else { A12.onload = A10; } function A9() {
/*@cc_on @*/
/*@if (@_jscript_version >= 0)
	A1 = true;
	return;
@end @*/
if (/KHTML|WebKit/i.test(navigator.userAgent)) { A3 = true; } else if (A6.addEventListener) { A2 = true; } else { A4 = true; } } function A10() { if (A0) { return; } A0 = true; A12.clearInterval(A5); A5 = null; A11(); } }
OnDOMLoad_5545(avInitiateAle_5545);